version: '3.8'

services:

  app:
#    build: .                //use this instead of image for local testing
    image: gauri1498/dockerbasic-springbootcrud:v3
    container_name: docker-springbootapp

    ports:
      - "8080:8080"

    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dockertest
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  mysql:
    image: mysql:8
    container_name: mysql-container

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockertest

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: